name: to_do
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^1.1.1



dev_dependencies:
  build: ^2.2.1
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.1.1


flutter:
  uses-material-design: true